---
name: ArtMapPM
main: xenialdan\ArtMapPM\Loader
version: 0.0.0
api:
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
load: POSTWORLD
authors:
- XenialDan
depends:
- MapAPI
permissions:
  artmap.admin:
    description: grants administrative override/deletion priveleges
    default: op
  artmap.artist:
    description: allows players to use artmap
    default: op
...
